### ISSUE TITLE
UnhandledPromiseRejectionWarning: HttpError: Empty value for parameter 'sha': undefined

### ISSUE THREAD

**Issue by joebowbeer** [slavcodev/coverage-monitor-action#16]
In version 1.1.0, I'm seeing unhandled promise rejection because of missing `sha` parameter.

The action succeeds in node12, but as the message says it may fail in the future.

## Details

```
(node:2742) UnhandledPromiseRejectionWarning: HttpError: Empty value for parameter 'sha': undefined
    at /home/runner/work/_actions/slavcodev/coverage-monitor-action/1.1.0/dist/index.js:7308:15
    at Array.forEach (<anonymous>)
    at /home/runner/work/_actions/slavcodev/coverage-monitor-action/1.1.0/dist/index.js:7276:12
    at Array.forEach (<anonymous>)
    at validate (/home/runner/work/_actions/slavcodev/coverage-monitor-action/1.1.0/dist/index.js:7249:23)
(node:2742) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2742) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by khajvahmac** [comment]
Here is the fix https://github.com/slavcodev/coverage-monitor-action/pull/17

**Comment by slavcodev** [comment]
Thank you. I'll check the issue and fix asap.
