### ISSUE TITLE
[Crash] Empty sha parameter with dependabot PRs

### ISSUE THREAD

**Issue by Yserz** [slavcodev/coverage-monitor-action#23]
Hey, thx for this nice action.

Unfortunately we have a problem with PRs that are created from [dependabot](https://dependabot.com/) while PRs created from normal contributors are fine.

## Details

Here's the stacktrace:
```
(node:3598) UnhandledPromiseRejectionWarning: HttpError: Empty value for parameter 'sha': undefined
    at /home/runner/work/_actions/slavcodev/coverage-monitor-action/1.1.0/dist/index.js:7308:15
    at Array.forEach (<anonymous>)
    at /home/runner/work/_actions/slavcodev/coverage-monitor-action/1.1.0/dist/index.js:7276:12
    at Array.forEach (<anonymous>)
    at validate (/home/runner/work/_actions/slavcodev/coverage-monitor-action/1.1.0/dist/index.js:7249:23)
(node:3598) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3598) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Environment variables:
GITHUB_SHA = caf11e4b868bd653aca52a063534eeefe79acdc4
GITHUB_REF = refs/pull/870/merge
GITHUB_CONTEXT = {
  ...
  "sha": "caf11e4b868bd653aca52a063534eeefe79acdc4",
  ...
}

Please let me know if you need more context.

**Comment by Yserz** [comment]
Ah, there is an update. Will try 1.2.0....

**Comment by Yserz** [comment]
Alright, 1.2.0 fixed the issue. I'll close this ticket :)
